import os
import importlib.util
from typing import Dict, Any, Callable
from pydantic import BaseModel
import logging

logger = logging.getLogger(__name__)

class PlaybookSkill(BaseModel):
    name: str
    description: str
    entrypoint: Callable
    metadata: Dict[str, Any]

class SkillRegistry:
    """
    Registry for loading and serving procedurally generated Python 
    skills compiled by AutoSwarm's continuous learning loop.
    """
    def __init__(self, skills_dir: str = None):
        self.skills_dir = skills_dir or os.environ.get("AUTOSWARM_SKILLS_DIR", "/var/lib/autoswarm/skills")
        self.skills: Dict[str, PlaybookSkill] = {}
        
    def load_skills(self):
        """
        Dynamically imports all `.py` files inside the skills directory.
        These are generated from successful ACP QA Oracle compilations.
        """
        if not os.path.exists(self.skills_dir):
            logger.warning(f"Skills directory {self.skills_dir} not found. Starting with empty registry.")
            return

        for filename in os.listdir(self.skills_dir):
            if filename.endswith(".py") and not filename.startswith("__"):
                skill_name = filename[:-3]
                path = os.path.join(self.skills_dir, filename)
                try:
                    spec = importlib.util.spec_from_file_location(skill_name, path)
                    module = importlib.util.module_from_spec(spec)
                    spec.loader.exec_module(module)
                    
                    if hasattr(module, "SKILL_ENTRYPOINT"):
                        self.skills[skill_name] = PlaybookSkill(
                            name=skill_name,
                            description=getattr(module, "SKILL_DESCRIPTION", "Autogenerated Skill"),
                            entrypoint=module.SKILL_ENTRYPOINT,
                            metadata=getattr(module, "SKILL_METADATA", {})
                        )
                        logger.info(f"Loaded skill: {skill_name}")
                except Exception as e:
                    logger.error(f"Failed to load skill {skill_name} from {path}: {e}")

    def get_skill(self, name: str) -> PlaybookSkill:
        return self.skills.get(name)

    def list_skills(self) -> Dict[str, str]:
        return {name: skill.description for name, skill in self.skills.items()}

# Singleton instance
registry = SkillRegistry()
