apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autoswarm

resources:
  - configmap.yaml
  - org-config.yaml
  - service-account.yaml
  - nexus-api.yaml
  - office-ui.yaml
  - colyseus.yaml
  - admin.yaml
  - admin-external-secret.yaml
  - gateway.yaml
  - workers.yaml
  - service-monitors.yaml
  - pdb.yaml
  - hpa.yaml
  - backup-cronjob.yaml
  - keda-scaledobject.yaml
  - keda-trigger-auth.yaml

commonLabels:
  app.kubernetes.io/part-of: autoswarm-office
  app.kubernetes.io/managed-by: kustomize
