records:
  - type: CNAME
    name: api.selva.town
    content: selva.cfargotunnel.com
    proxied: true
  - type: CNAME
    name: selva.town
    content: selva.cfargotunnel.com
    proxied: true
  - type: CNAME
    name: www.selva.town
    content: selva.cfargotunnel.com
    proxied: true
  - type: CNAME
    name: ws.selva.town
    content: selva.cfargotunnel.com
    proxied: true
  - type: CNAME
    name: admin.selva.town
    content: selva.cfargotunnel.com
    proxied: true
