records:
  - type: CNAME
    name: agents-api.selva.town
    content: autoswarm-office.cfargotunnel.com
    proxied: true
  - type: CNAME
    name: agents.selva.town
    content: autoswarm-office.cfargotunnel.com
    proxied: true
  - type: CNAME
    name: agents-ws.selva.town
    content: autoswarm-office.cfargotunnel.com
    proxied: true
  - type: CNAME
    name: agents-admin.selva.town
    content: autoswarm-office.cfargotunnel.com
    proxied: true
