records:
  - type: CNAME
    name: agents-api.madfam.io
    content: autoswarm-office.cfargotunnel.com
    proxied: true
  - type: CNAME
    name: agents.madfam.io
    content: autoswarm-office.cfargotunnel.com
    proxied: true
  - type: CNAME
    name: agents-ws.madfam.io
    content: autoswarm-office.cfargotunnel.com
    proxied: true
  - type: CNAME
    name: agents-admin.madfam.io
    content: autoswarm-office.cfargotunnel.com
    proxied: true
