tunnel: autoswarm-office
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: api.selva.town
    service: http://nexus-api.autoswarm.svc.cluster.local:80
  - hostname: hall.selva.town
    service: http://office-ui.autoswarm.svc.cluster.local:80
  - hostname: ws.selva.town
    service: http://colyseus.autoswarm.svc.cluster.local:80
  - hostname: admin.selva.town
    service: http://admin.autoswarm.svc.cluster.local:80
  - service: http_status:404
